$w insert end "\n\n\[I]\n\n" pagenr
$w insert end "VORREDE." h1
$w insert end "\n\nEs hätte meinem bruder zugestanden an der spitze "
$w insert end "dieses bandes, dessen grösztes stück von ihm herrührt, "
$w insert end "den blick rückwärts zu wenden und sich über mehr als "
$w insert end "einen der hier die vielseitigste erwägung fordernden "
$w insert end "gegenstände mit aufmerksamer anmut, wie sie ihm "
$w insert end "eigen war, auszusprechen. trauernd um seinen hingang "
$w insert end "musz ich es sein, der wieder vortritt und das wort "
$w insert end "ergreift, seines talents und seiner ratschläge, sowie "
$w insert end "überhaupt seiner edeln mithülfe geht die fortsetzung "
$w insert end "des werkes nun für immer verlustig. "
$w insert end "\nEr arbeitete langsam und leise, aber rein und sauber; "
$w insert end "wenn sein verspäten einigemal gefahr brachte und die "
$w insert end "geduld der leser auf die probe stellte, so werden sie sich "
$w insert end "nachher an der feinen abgrenzung und ausführung alles "
$w insert end "dessen, was er lieferte, erfreut haben. in milder, gefallender "
$w insert end "darstellung war er mir, wo wir etwas zusammen "
$w insert end "thaten, stets überlegen. "
$w insert end "\nAngemerkt zu werden verdient, dasz er mit dem "
$w insert end "buchstaben D, welchen er sich zuerst auserlesen hatte "
$w insert end "(I, "
$w insert end "LXIV" stext
$w insert end "), genau und ohne dasz davon ein wörtchen fehlte "
$w insert end "zu ende gelangt war, als ihn der tod wegnahm. seine "
$w insert end "mühe krönte sich durch befriedigenden abschlusz. jene "
$w insert end "wahl war doch mehr zufällig als in irgend einer vorliebe "
$w insert end "begründet, für ein wörterbuch fallen alle buchstaben "
$w insert end "gleich schwer und selbst die leichter scheinenden erheben "
$w insert end "allenthalben anstosz. im deutschen gewähren "
$w insert end "die vier flüssigen angenehmste arbeit, weil hier der laut "
$w insert end "feststeht und keine partikelzusammensetzungen vorkommen, "
$w insert end "wogegen bei den vocalen und stummen buchstaben "
$w insert end "ihre schwankende abstufung vielfach stört und "
$w insert end "anstrengt. unsere S und W zeigen den gröszten umfang, "
$w insert end "während im lateinischen, griechischen, slavischen "
$w insert end "und auch im sanskrit, jener partikeln wegen, P weit "
$w insert end "überwiegt, das bei uns fast zurücktritt. es ist wahr, die "
$w insert end "endlose aufzählung der partikelfülle, auf die ich gleich "
$w insert end "nachher noch zu sprechen komme, ermüdet, führt aber "
$w insert end "auch zu wichtigen schlüssen; in welchen theil des "
$w insert end "wortvorrats man immer greife, wird, nach überwundner "
$w insert end "erster scheu, man sich bald davon angezogen fühlen. "
$w insert end "\nMein bruder ist in einigen dingen, die ich verabredet "
$w insert end "glaubte und für die ich beim beginn unausweichlich einen "
$w insert end "ton angeben muste, wieder abgewichen, sei es dasz er "
$w insert end "sich eigner angewöhnungen nicht entschlagen konnte "
$w insert end "oder einer ihm zusagenden änderung den vorzug liesz. "
$w insert end "mir that dies leid, weil dadurch der in einem wörterbuch "
$w insert end "\n\n\[II]\n\n" pagenr
$w insert end "wünschenswerthen äuszeren gleichförmigkeit abbruch "
$w insert end "geschah; jetzt aber möchte ich nicht, dasz er anders "
$w insert end "verfahren wäre, weil mir auch in solchen nebensachen "
$w insert end "seine ganze eigenthümlichkeit rührend entgegentritt. "
$w insert end "das publicum wird uns beiden diese ungleichheit verzeihen "
$w insert end "und sie leicht ertragen, ich will hier näher darauf "
$w insert end "eingehen. "
$w insert end "\nEr hat viele der gebrauchten abkürzungen wieder "
$w insert end "aufgelöst und nicht wenige anführungen voller ausgehoben, "
$w insert end "wodurch der eindruck allerdings anschaulicher "
$w insert end "wird; doch bleibt zu bedenken, dasz diese einrichtung, "
$w insert end "wenn sie für das ganze werk beibehalten werden sollte, "
$w insert end "bedeutenden raum mehr kosten würde, auf dessen ersparung "
$w insert end "um vieler ursachen willen jedes wörterbuch "
$w insert end "bedacht zu nehmen hat. man darf da, wo auch die gedrängtere "
$w insert end "darstellung ihren werth erhält, sich nicht so "
$w insert end "gehen lassen wie in andern schriften. gehäufte kürzungen "
$w insert end "können ekel erregen und ein buch unlesbar machen, "
$w insert end "mäszig verwandte dem überblick förderlich sein. "
$w insert end "\nIch sehe nicht ein, und habe mich darüber schon ausgesprochen, "
$w insert end "warum in einem deutschen wörterbuche "
$w insert end "eins der leichtesten und natürlichsten mittel des verständnisses "
$w insert end "von der hand gewiesen werden solle, nemlich "
$w insert end "die anwendung des lateins oder überhaupt einer "
$w insert end "fremden andern sprache. die worterklärung gewinnt "
$w insert end "dadurch augenblicklich einen halt, den ihr ein auseinandersetzen "
$w insert end "in der eignen sprache nicht so schnell gewährt, "
$w insert end "und weitere deutungen können sich dann leicht "
$w insert end "anschlieszen. das lateinische wort soll den begrif "
$w insert end "weder von grund aus festigen noch erschöpfen, das "
$w insert end "bleibt der nachfolgenden erörterung und den belegstellen "
$w insert end "überlassen; aber es zieht schon an aus einer uns "
$w insert end "urverwandten, klaren sprache den oft nah entsprechenden "
$w insert end "oder aus der ferne winkenden ausdruck vor augen "
$w insert end "zu haben. einem bloszen auf gewöhnliche definition "
$w insert end "hinauslaufenden handwörterbuch wäre die lateinische "
$w insert end "beigabe entbehrlich, einem ausführlichen gelehrten "
$w insert end "wörterbuch wird sie wo nicht nothwendig, wenigstens "
$w insert end "sehr ersprieszlich. niemand erblickt in der bezeichnung "
$w insert end "des dreifachen geschlechts durch m. f. n. etwas "
$w insert end "pedantisches oder wüste eine gleichgute an deren stelle "
$w insert end "zu setzen; warum soll die in derselben sprache, aus "
$w insert end "welcher diese abkürzungen geschöpft werden, erfolgende "
$w insert end "angabe der wortbedeutung verwerflich sein? es "
$w insert end "kommt hinzu, dasz unsere alten wörterbücher, "
$w insert end "D" ai
$w insert end "ASYPODIUS" ar
$w insert end ", "
$w insert end "\n\n\[III]\n\n" pagenr
$w insert end "F" ai
$w insert end "RISIUS" ar
$w insert end ", "
$w insert end "M" ai
$w insert end "AALER" ar
$w insert end ", "
$w insert end "H" ai
$w insert end "ENISCH" ar
$w insert end ", bis auf "
$w insert end "S" ai
$w insert end "TIELER" ar
$w insert end " und "
$w insert end "F" ai
$w insert end "RISCH" ar
$w insert end " abwärts, wörter und phrasen lateinisch wiedergeben "
$w insert end "und dasz es daran liegen musz ihre oft treffend "
$w insert end "gewählten ausdrücke zu behalten und anzuführen, "
$w insert end "gleich unentbehrlich bleibt die angabe der lateinischen "
$w insert end "pflanzen- und thiernamen, wie sie im system hergebracht "
$w insert end "ist; ein groszer theil der auslegung würde also "
$w insert end "unvermeidlich lateinisches aussehen gewinnen, wer "
$w insert end "sich darüber hinaus setzt, wie sollte er in der lateinischen "
$w insert end "erklärung überhaupt unerträgliche buntheit des "
$w insert end "vortrags finden? ein historisches, etymologisches wörterbuch "
$w insert end "kann nicht anders als viele sprachen nebeneinander "
$w insert end "verwenden. Unser deutsches wörterbuch soll "
$w insert end "nicht nur für Deutsche in engerm sinne sein, sondern "
$w insert end "sich auch zu Scandinaven, Niederländern, Engländern, "
$w insert end "Franzosen und andern Welschen, zu Slaven, Ungern, "
$w insert end "Finnen erstrecken; diesen völkern allen oder den meisten "
$w insert end "ist mehr mit dem beigefügten lateinischen worte "
$w insert end "gedient als mit einer deutschverfaszten erklärung, wie "
$w insert end "uns ja selbst ein glossar der sanskritsprache oder der "
$w insert end "finnischen, ungrischen, russischen, litauischen wenig "
$w insert end "helfen würde, dem eine blosz esoterische zustände, "
$w insert end "hingegen die exoterische lateinische oder französische, "
$w insert end "deutsche auslegung abgienge. sie unterdrücken heiszt "
$w insert end "demnach die verbreitung des wörterbuchs in das ausland "
$w insert end "hemmen oder mindern. Man kann endlich auch "
$w insert end "aufstellen, dasz ein gutes wörterbuch nicht einmal auf "
$w insert end "die gegenwärtige und nächste zeit beschränkt, sondern "
$w insert end "bestimmt sein solle länger zu dauern, wie jene dictionare "
$w insert end "von "
$w insert end "D" ai
$w insert end "ASYPODIUS" ar
$w insert end " und "
$w insert end "M" ai
$w insert end "AALER" ar
$w insert end " nun schon jahrhunderte "
$w insert end "lang gebraucht werden; hätten sie nicht lateinisch, "
$w insert end "sondern deutsch erklärt, sie würden oft schon "
$w insert end "unbestimmt geworden sein, auf gleiche weise aber auch "
$w insert end "die heutigen deutschen erklärungen, ohne die stütze "
$w insert end "der lateinischen einer fernen zukunft vielleicht nicht "
$w insert end "mehr ausgereicht haben. Aus allen diesen gründen war "
$w insert end "es mir nicht recht das lateinische wort bei meinem bruder "
$w insert end "oft zu vermissen. "
$w insert end "\nIch war bestrebt in jedem artikel den unterschied "
$w insert end "zu beobachten, dasz die fortlaufende reihe von belegen "
$w insert end "gleicher art durch ein semicolon und erst, wenn sie zu "
$w insert end "ende gienge, durch den punct bezeichnet würde, weil "
$w insert end "daran zu liegen scheint, die aufmerksamkeit auf diese "
$w insert end "reihen und deren schlusz zu lenken. er liesz das semicolon "
$w insert end "weg und setzte überall puncte. Dagegen folgte "
$w insert end "er einer wahrscheinlich in England aufgebrachten, wie "
$w insert end "mich dünkt, tadelhaften neuerung, den punct da, wo "
$w insert end "eine angeführte stelle aufhört, ganz zu unterdrücken, "
$w insert end "und das unmittelbar folgende citat mit einem groszen "
$w insert end "buchstaben zu bezeichnen, gleichviel ob dieser ihm als "
$w insert end "eigennamen zustehe oder nicht. dieselbe störende "
$w insert end "citierweise findet sich auch im mhd. wörterbuch angenommen. "
$w insert end "sie thut keinen schaden, wiewol sie ohne "
$w insert end "vortheil ist, sobald auf griechische stellen der lateinische "
$w insert end "name folgt, z. b. in "
$w insert end "H" ai
$w insert end "EINR." ar
$w insert end " J" ai
$w insert end "ACOBIS" ar
$w insert end " comicae "
$w insert end "dictionis index, weil hier die verschiedenheit der schrift "
$w insert end "genug sondert. wo dies aber nicht der fall ist, scheint "
$w insert end "unnatürlich, dasz ein geschlossener satz seines puncts "
$w insert end "entbehre und gleichsam in den unmittelbar darauf gesetzten "
$w insert end "namen fortgehe, wie sich zumal übel ausnimmt, "
$w insert end "wenn das citat mit einem das. = daselbst beginnt. es "
$w insert end "war schon von übel, dasz einige zwischen dem schlusz "
$w insert end "\n\n\[IV]\n\n" pagenr
$w insert end "der stelle und dem citat statt des puncts ein bloszes "
$w insert end "comma brauchten, wie z. b. bei "
$w insert end "A" ai
$w insert end "DELUNG" ar
$w insert end " geschieht. "
$w insert end "raum gespart wird weder durch das comma noch durch "
$w insert end "das unterbleiben jedes zeichens, weil man dann das "
$w insert end "letzte wort von dem anhebenden citat weiter abstehen "
$w insert end "läszt. jener misbrauch groszer buchstaben beeinträchtigt "
$w insert end "aber deren auf eigennamen einzuschränkenden und "
$w insert end "alsdann rechten, nützlichen gebrauch. das wörterbuch "
$w insert end "macht eine unmenge von citaten nöthig und darf auf "
$w insert end "jede kleinliche genauigkeit dabei dringen. "
$w insert end "\nWichtiger sein mag eine andere lossagung von der "
$w insert end "im wörterbuch sonst beachteten regel in bezug auf die "
$w insert end "sich an das verbum heftenden partikeln, und hiervon ist "
$w insert end "etwas genauer zu reden. ursprünglich stehen alle partikeln "
$w insert end "neben dem verbum los und ledig, doch schon im "
$w insert end "sanskrit, im griechischen und lateinischen sehen wir "
$w insert end "viele zu gangbaren bestimmungen der bedeutung vorn "
$w insert end "mit dem verbum verknüpft, ohne dasz sie sich wieder "
$w insert end "von dieser stelle frei machen. auch die mehrzahl der "
$w insert end "gothischen und lateinischen partikeln erscheint bereits "
$w insert end "in solcher lage meistens untrennbar, obgleich sich z. b. "
$w insert end "zwischen goth. ga und das verbum andere wörter "
$w insert end "schieben und "
$w insert end "P" ai
$w insert end "LAUTUS" ar
$w insert end " noch i prae für praei sagen kann. "
$w insert end "merkwürdige und schöne eigenheit hochdeutscher "
$w insert end "mundart von der ältesten zeit bis auf heute bleibt es "
$w insert end "aber, dasz sie einer groszen zahl von partikeln neben "
$w insert end "dem verbum in genau bestimmter wortstellung ihre "
$w insert end "trennbarkeit bewahrt, sicherste probe liefert dann jedesmal "
$w insert end "der imperativ, welchem die partikel immer los "
$w insert end "nachfolgt, jenem i prae entspricht unser geh vor. ganz "
$w insert end "untrennbarer partikeln zählen wir nhd. nur sechse: "
$w insert end "be, ent, er, ge, ver, zer; halbtrennbarer eben soviel: "
$w insert end "durch, hinter, über, um, unter, wider, d. h. nach verschiedenheit "
$w insert end "der bedeutungen werden sie bald untrennbar, "
$w insert end "bald trennbar. alle andern sind trennbar und die "
$w insert end "wortstellung bestimmt, ob sie sich vorheften oder ablösen. "
$w insert end "weggesehen von diesen aus der grammatik hinlänglich "
$w insert end "bekannten verhältnissen läszt sich nicht verkennen, "
$w insert end "dasz schon ahd. ein groszer trieb der partikelanfügung "
$w insert end "oder der zusammensetzung des verbums mit "
$w insert end "partikeln waltet, wie ein gleichartiger haft derselben "
$w insert end "partikeln an dem nomen zu erkennen gibt, jedwede zusammensetzung "
$w insert end "mit dem nomen wird aber unauflösbar. "
$w insert end "während wir in abgehen, hingehen, aufgehen noch "
$w insert end "trennbare partikeln dem verbum zugesellen, sind sie in "
$w insert end "abgang, hingang, aufgang untrennbar geworden und "
$w insert end "doch musz dem zusammengefügten nomen ein zusammengefügtes "
$w insert end "verbum vorangegangen sein, weil die nominalvorstellung "
$w insert end "wesentlich auf der verbalen beruht. "
$w insert end "ein ahd. apaganc abscessus, danatrip repudium, hinafart "
$w insert end "discessus, ein mhd. abelouf, dankêre abitus sind uns "
$w insert end "also bürge dafür, dasz damals schon ein näher verbundnes "
$w insert end "apagangan, danatrîpan, hinafaran, abeloufen, "
$w insert end "dankêren galten. diese neigung anzufügen hat im verlauf "
$w insert end "der zeit noch zugenommen, wie wir romanische "
$w insert end "sprachen vergleichend leicht gewahren, z. b. dem freien "
$w insert end "it. andar via, volar via steht unser gebundnes weggehen, "
$w insert end "wegfliegen zur seite. "
$w insert end "\nHat es nun damit die vorgetragne bewandtnis, so "
$w insert end "leuchtet ein, dasz in dem wörterbuch solche zusammensetzungen "
$w insert end "nicht zu übersehen, sondern hervorzuheben "
$w insert end "sind. ich kann es nicht folgerichtig finden, dasz "
$w insert end "\n\n\[V]\n\n" pagenr
$w insert end "alle mit durch gebundnen verba, neben sorgfältiger "
$w insert end "unterscheidung ihrer trennbarkeit und untrennbarkeit, "
$w insert end "einzeln und alphabetisch eingetragen, die an den partikeln "
$w insert end "dannen, dahin, daher, danieder, daran, darein "
$w insert end "haftenden aber unter diesen partikeln verzeichnet und "
$w insert end "abgehandelt werden. das heiszt grammatisch verfahren, "
$w insert end "nicht lexicalisch. im lexicon will man alphabetisch aufschlagen "
$w insert end "und zur stelle finden, was man sucht, gerade "
$w insert end "wie abgehen, annehmen, aufnehmen, eingehen, eindringen "
$w insert end "als selbständige wortbildungen, nicht unter "
$w insert end "gehen, nehmen, noch weniger unter an, auf, ein gesucht "
$w insert end "werden. bei daher sp. 679-684 sind sogar mehrere "
$w insert end "classen abgesondert, nach denen sich das wörterbuch "
$w insert end "gar nicht richten kann, oder alle unter ab, an, auf, aus "
$w insert end "eingestellten verba müsten sich auch aus ihrer reihe "
$w insert end "reiszen und unter den betreffenden partikeln aufführen "
$w insert end "lassen. ohne zweifel haben grammatik und wörterbuch "
$w insert end "ihre eignen gesichtspuncte und wissen daraus besondere "
$w insert end "vortheile zu ziehen. Im verlaufe des werks und "
$w insert end "an rechter stelle sollen dem hier erörterten noch "
$w insert end "manche einzelne bestimmungen, vielleicht auch einschränkungen "
$w insert end "zutreten. "
$w insert end "\nAn den hervorgehobnen, keineswegs bedeutsamen "
$w insert end "unähnlichkeiten der behandlung würde der leser alsogleich "
$w insert end "erkennen, wenn er es nicht ohnehin schon wüste, "
$w insert end "welchem von beiden verfassern jede einzelne stelle "
$w insert end "beizulegen sei; aus mehrern bächen ist verschiednes "
$w insert end "und doch meistens ähnliches gewässer in éinen flusz "
$w insert end "zusammengeronnen. "
$w insert end "\nLust hätte ich wol, mich in betrachtungen über die "
$w insert end "natur und erfolge eines wörterbuchs tiefer versenkend, "
$w insert end "einen wesentlichen unterschied zwischen sprachforschung "
$w insert end "und philologie geltend zu machen. denn es gibt "
$w insert end "eine menge verdienstvoller, scharfsinniger philologen, "
$w insert end "die für die hauptzwecke der sprachforschung, für grammatik "
$w insert end "und etymologie, weder beruf noch geschick gezeigt "
$w insert end "\n\n\[VI]\n\n" pagenr
$w insert end "und keine von beiden durch neue entdeckungen "
$w insert end "bereichert haben. diese an folgerungen fruchtbare verschiedenheit "
$w insert end "ist bisher noch nicht wie es sein sollte erkannt "
$w insert end "und entfaltet worden. es könnte aber scheinen, "
$w insert end "als wollte ich damit mein vermögen an das des geliebten "
$w insert end "bruders halten, da ich doch viel mehr auf die sache "
$w insert end "als auf die leute, viel weniger auf ihn als auf andere "
$w insert end "sehen würde, und sein verlust ist allzu frisch als dasz "
$w insert end "ich auszusprechen wagte, was ihn nur von ferne berührte. "
$w insert end "\nNoch habe ich dankbar die zu nennen, durch deren "
$w insert end "ansehnliche beiträge auch dieser band des wörterbuchs "
$w insert end "gefördert wurde. "
$w insert end "R" ai
$w insert end "IEDELS" ar
$w insert end " unermüdende samlung hielt "
$w insert end "bis zu seinem tode an. "
$w insert end "W" ai
$w insert end "EIGAND" ar
$w insert end " hat die seltne kraft "
$w insert end "und den noch seltneren willen neben einer eignen treflichen "
$w insert end "arbeit auch die fremde liebgewonnene durch "
$w insert end "reiche beiträge zu unterstützen; von "
$w insert end "M" ai
$w insert end "ENGE" ar
$w insert end " laufen immer "
$w insert end "die reinlichsten, sichersten auszüge ein. nicht "
$w insert end "minder fleiszig und brauchbar sind die von "
$w insert end "K. W" ai
$w insert end "OLFF" ar
$w insert end " in "
$w insert end "Stuttgart, "
$w insert end "P" ai
$w insert end "ALM" ar
$w insert end " in Breslau, "
$w insert end "C" ai
$w insert end "RECELIUS" ar
$w insert end " in Elberfeld, "
$w insert end "E" ai
$w insert end "RK" ar
$w insert end " in Berlin, "
$w insert end "R" ai
$w insert end "ÜDEL" ar
$w insert end " in Nürnberg, "
$w insert end "S" ai
$w insert end "EIDEMANN" ar
$w insert end " in Eschdorf "
$w insert end "empfangnen. "
$w insert end "H" ai
$w insert end "EDWIG" ar
$w insert end " und "
$w insert end "E" ai
$w insert end "LEONORE" ar
$w insert end " W" ai
$w insert end "ALLOT" ar
$w insert end ", zwei "
$w insert end "Mainzerinnen, jetzt in Heidelberg, haben ungemein "
$w insert end "sorgfältige mittheilungen gemacht. über excerpt und "
$w insert end "beitrag hinaus reicht die von "
$w insert end "H" ai
$w insert end "ILDEBRAND" ar
$w insert end " fortwährend "
$w insert end "und vorzüglich dem buchstaben D erwiesene, auf volle "
$w insert end "befähigung zur mitarbeit schlieszen lassende hülfe. "
$w insert end "unter den im druck erschienenen neuen werken wäre "
$w insert end "vor allem "
$w insert end "G" ai
$w insert end "UTZEITS" ar
$w insert end " wörterschatz der deutschen sprache "
$w insert end "Livlands zu erwähnen, welche ausgezeichnete arbeit "
$w insert end "vorerst nur den buchstaben A und B zu statten kommt "
$w insert end "und beträchtliche nachträge und ergänzungen für den "
$w insert end "ersten band gewährt. "
$w insert end "\nDie fortsetzung des quellenverzeichnisses ist lediglich "
$w insert end "H" ai
$w insert end "IRZELS" ar
$w insert end " güte und genauer einsicht selbst zu verdanken. "
$w insert end "\n\n"
$w insert end "Berlin 6. februar 1860."
$w insert end "\nJACOB GRIMM." rtext