$w insert end "\n\n\[I]\n\n" pagenr
$w insert end "VORWORT." h1
$w insert end "\n\nNach nicht viel mehr als fünf jahren seit dem "
$w insert end "erscheinen des achten bandes lege ich den neunten "
$w insert end "vor. das wäre nicht möglich gewesen, wenn nicht "
$w insert end "die auf dem titel genannten mitarbeiter, die schon "
$w insert end "einen guten theil des vorigen haben schaffen helfen, "
$w insert end "auch diesem bande ihre ganze und begeisterte hingabe "
$w insert end "gewidmet hätten. so konnten wir, unter verzicht auf "
$w insert end "andere arbeitsmethoden, in enger fühlung und voller "
$w insert end "harmonie, wie ein wol eingespieltes quartett, unsere "
$w insert end "aufgabe vollführen. wir glauben, damit zugleich die "
$w insert end "beste antwort gegeben zu haben auf mancherlei äuszerungen "
$w insert end "in der presse, die an die fortsetzung des "
$w insert end "wörterbuchs anknüpften und die nicht immer von "
$w insert end "wolwollen für das nationale werk, noch weniger von "
$w insert end "sachkenntnis zeugten. was ich in der vorrede zum "
$w insert end "\n\n\[II]\n\n" pagenr
$w insert end "sechsten bande 1885 gesagt habe, hat noch immer "
$w insert end "seine giltigkeit; es ist ja auch bequemer, programme "
$w insert end "auf das papier hinzuwerfen, als in treuer ausführender "
$w insert end "arbeit auszuharren. wir thun unser mögliches, das "
$w insert end "werk innerhalb seiner grenzen, die wol erweitert "
$w insert end "werden können und erweitert worden sind, die aber "
$w insert end "ohne schaden für es selbst nicht niedergerissen werden "
$w insert end "sollen, auf wissenschaftliche höhe zu führen. hastige "
$w insert end "arbeit wird uns niemand vorwerfen, der das ruhige "
$w insert end "und stetige herauskommen unserer lieferungen beachtet "
$w insert end "hat; aber wir denken, ein werk, das nunmehr "
$w insert end "bald fünfzig jahre im erscheinen begriffen ist, hat "
$w insert end "anspruch darauf, nun einmal fertig zu werden. und "
$w insert end "wir wünschen, auch ferner verbunden unser theil dazu "
$w insert end "beizutragen. "
$w insert end "\n\n     Göttingen, 15. februar 1899. "
$w insert end "\nM. HEYNE.     " rtext