$w insert end "\n\n\[I]\n\n" pagenr
$w insert end "VORWORT." h1
$w insert end "\n\nIndem ich mit diesen zeilen eine achtjährige, neben "
$w insert end "der amtlichen thätigkeit in verschiedenen lagen und "
$w insert end "stimmungen durchgeführte arbeit zum abschlusz bringe, "
$w insert end "bin ich mir wol bewuszt, dasz sie hinter den anforderungen, "
$w insert end "die man an das vor nahezu vierzig jahren "
$w insert end "begonnene werk heute zu machen pflegt, in mehr als "
$w insert end "einer hinsicht zurückgeblieben ist. zunächst kann ich "
$w insert end "mich jener wuchtigen gelehrsamkeit und belesenheit "
$w insert end "nicht rühmen, wie sie namentlich aus G und K entgegentritt; "
$w insert end "sodann war ich von meinen früheren lexikalischen "
$w insert end "arbeiten her an eine gewisse knappheit und "
$w insert end "kürze des ausdrucks gewöhnt, die ich auch hier nicht "
$w insert end "ganz abstreifen und dem \"groszen stile\" anpassen "
$w insert end "konnte. dieser mangel ist aber vielleicht der übersichtlichkeit "
$w insert end "meiner arbeit zu gut gekommen und hat "
$w insert end "ihr mehr den charakter eines wörterbuchs gewahrt, "
$w insert end "in dem man das gesuchte ohne groszen zeitverlust "
$w insert end "finden will. "
$w insert end "\nDas in diesem bande verarbeitete material würde "
$w insert end "freilich an wert und umfang bedeutend gewonnen "
$w insert end "haben, wenn ich zur ergänzung des höchst mangelhaften, "
$w insert end "im vorworte zum sechsten bande geschilderten "
$w insert end "zettelapparates eine grosze bibliothek (wie z. b. die zeitweise "
$w insert end "besuchte Münchener hof- und staatsbibliothek) "
$w insert end "andauernd hätte benutzen können. unsere universitätsbibliothek "
$w insert end "konnte mir namentlich für das wichtige "
$w insert end "16. und 17. jahrhundert verhältnismäszig wenig "
$w insert end "bieten, so dasz ich hauptsächlich auf meine eigene, für "
$w insert end "\n\n\[II]\n\n" pagenr
$w insert end "diesen zweck erst allmählich und nach gelegenheit vervollständigte "
$w insert end "büchersammlung angewiesen war. dazu "
$w insert end "kamen noch kleinere oder gröszere beiträge einiger "
$w insert end "fachgenossen und freunde, denen gleich hier mein "
$w insert end "wärmster dank ausgesprochen und auch auf jene ausgedehnt "
$w insert end "werden soll, die durch wolwollende anzeige "
$w insert end "einzelner lieferungen den einsam arbeitenden zur ausdauer "
$w insert end "ermuntert haben. "
$w insert end "\nIn den fremdwörterreichen P und Q wird man vielleicht "
$w insert end "die aufnahme mancher unberechtigter lehnwörter "
$w insert end "tadeln; eine grenze war da um so schwerer zu "
$w insert end "ziehen, als viele derselben, die ich wol ausgeschlossen "
$w insert end "hätte, von "
$w insert end "J. G" ai
$w insert end "RIMM" ar
$w insert end " selbst zur aufnahme bereit gestellt "
$w insert end "waren. "
$w insert end "\nDie neu hinzugekommenen, oder in neuen ausgaben "
$w insert end "(oder neudrucken) erschienenen quellen sind nebst "
$w insert end "einigen hilfsmitteln im nachfolgenden verzeichnisse aufgeführt; "
$w insert end "wo ich eine andere als die bisher citierte "
$w insert end "ausgabe benutzen muszte, ist sie an ort und stelle "
$w insert end "immer näher bezeichnet worden. nicht ins verzeichnis "
$w insert end "aufgenommen wurden jene quellenschriften, aus denen "
$w insert end "nur vereinzelte belege mitgetheilt werden konnten. "
$w insert end "\nDie von mir und andern zu diesem bande gesammelten "
$w insert end "nachträge können hier keine verwertung mehr "
$w insert end "finden, doch will ich bemerken, dasz das unbelegte "
$w insert end " n a c h a h m l i c h  (sp. 20) bei "
$w insert end "V" ai
$w insert end "OSS" ar
$w insert end " Hor. epist. 1, 19, 17 "
$w insert end "vorkommt, und dasz  n ä m l i c h  (sp. 345) auch von "
$w insert end "G" ai
$w insert end "ÖTHE" ar
$w insert end " gebraucht wird, z. b. 51, 136. "
$w insert end "\n   Würzburg, im januar 1889. "
$w insert end "\nM. v. LEXER.   " rtext