proc ShowDWBAbbr {w} {
   $w insert end "\n\neine einheitliche Regelung der Abkürzungspraxis erfolgte nicht."
   $w insert end " nur in bd. 1, sp. XCIf. findet sich eine kurze liste mit"
   $w insert end " abkürzungen grammatischer ausdrücke, die im folgenden mit"
   $w insert end " angeführt sind."
   $w insert end "\n\naao., a. a. o.\t\t\t\t\tam angegebenen ort"
   $w insert end "\naarg.\t\t\t\t\taargauisch"
   $w insert end "\nabb.\t\t\t\t\tabbildung"
   $w insert end "\nabdr.\t\t\t\t\tabdruck"
   $w insert end "\nabg.\t\t\t\t\taltbulgarisch"
   $w insert end "\nabl.\t\t\t\t\tablativ"
   $w insert end "\nabret.\t\t\t\t\taltbretonisch"
   $w insert end "\nabstr.\t\t\t\t\tabstraktum"
   $w insert end "\nabulg.\t\t\t\t\taltbulgarisch"
   $w insert end "\nacc., accus.\t\t\t\t\takkusativ"
   $w insert end "\nact.\t\t\t\t\taktiv(um)"
   $w insert end "\nadän.\t\t\t\t\taltdänisch"
   $w insert end "\nädän.\t\t\t\t\tälterdänisch"
   $w insert end "\nadj., adject.\t\t\t\t\tadjektiv, adjektivisch"
   $w insert end "\na. d. j.\t\t\t\t\taus dem jahre"
   $w insert end "\nadv.\t\t\t\t\tadverb"
   $w insert end "\nae.\t\t\t\t\taltenglisch"
   $w insert end "\na. e.\t\t\t\t\tam ende"
   $w insert end "\nafr.\t\t\t\t\taltfranzösisch, altfriesisch"
   $w insert end "\nafranz.\t\t\t\t\taltfranzösisch"
   $w insert end "\nafries., afrs.\t\t\t\t\taltfriesisch"
   $w insert end "\nafrz.\t\t\t\t\taltfranzösisch"
   $w insert end "\nags.\t\t\t\t\tangelsächsisch"
   $w insert end "\nahd.\t\t\t\t\talthochdeutsch"
   $w insert end "\nähnl.\t\t\t\t\tähnlich"
   $w insert end "\nai., aind.\t\t\t\t\taltindisch"
   $w insert end "\nair.\t\t\t\t\taltirisch"
   $w insert end "\naisl.\t\t\t\t\taltisländisch"
   $w insert end "\naital.\t\t\t\t\taltitalienisch"
   $w insert end "\nakelt.\t\t\t\t\taltkeltisch"
   $w insert end "\nakk.\t\t\t\t\takkusativ"
   $w insert end "\naksl., akslav.\t\t\t\t\taltkirchenslawisch"
   $w insert end "\nal.\t\t\t\t\talemannisch"
   $w insert end "\nalb., alban.\t\t\t\t\talbanisch"
   $w insert end "\nalem., alemann.\t\t\t\t\talemannisch"
   $w insert end "\nallg., allgem.\t\t\t\t\tallgemein"
   $w insert end "\nalph., alphab(et).\t\t\t\t\talphabetisch"
   $w insert end "\nält.\t\t\t\t\tälter"
   $w insert end "\naltd.\t\t\t\t\taltdeutsch"
   $w insert end "\naltenb.\t\t\t\t\taltenburgisch"
   $w insert end "\naltgutn.\t\t\t\t\taltgutnisch (altgotländisch)"
   $w insert end "\nalth., althd.\t\t\t\t\talthochdeutsch"
   $w insert end "\naltind.\t\t\t\t\taltindisch"
   $w insert end "\naltn.\t\t\t\t\taltnordisch"
   $w insert end "\nalts.\t\t\t\t\taltsächsisch"
   $w insert end "\namd.\t\t\t\t\taltmitteldeutsch"
   $w insert end "\nan.\t\t\t\t\taltnordisch"
   $w insert end "\nand.\t\t\t\t\taltniederdeutsch"
   $w insert end "\nanf., anfg.\t\t\t\t\tanfang"
   $w insert end "\nanfr., anfrk.\t\t\t\t\taltniederfränkisch"
   $w insert end "\nangels.\t\t\t\t\tangelsächsisch"
   $w insert end "\nanl.\t\t\t\t\tanlautend"
   $w insert end "\nanm.\t\t\t\t\tanmerkung"
   $w insert end "\nanord.\t\t\t\t\taltnordisch"
   $w insert end "\nanorg.\t\t\t\t\tanorganisch"
   $w insert end "\nanorw.\t\t\t\t\taltnorwegisch"
   $w insert end "\nanr.\t\t\t\t\tanrede"
   $w insert end "\näol.\t\t\t\t\täolisch"
   $w insert end "\napers.\t\t\t\t\taltpersisch"
   $w insert end "\nappenz.\t\t\t\t\tappenzellisch"
   $w insert end "\napreusz.\t\t\t\t\taltpreuszisch"
   $w insert end "\nar.\t\t\t\t\tarisch"
   $w insert end "\narab.\t\t\t\t\tarabisch"
   $w insert end "\naram.\t\t\t\t\taramäisch"
   $w insert end "\narm., armen.\t\t\t\t\tarmenisch"
   $w insert end "\narmor.\t\t\t\t\tarmorisch (altgallisch)"
   $w insert end "\naruss.\t\t\t\t\taltrussisch"
   $w insert end "\nas.\t\t\t\t\taltsächsisch"
   $w insert end "\naschwed.\t\t\t\t\taltschwedisch"
   $w insert end "\nasl., aslav.\t\t\t\t\taltslawisch"
   $w insert end "\nasp.\t\t\t\t\taspirata"
   $w insert end "\nä. spr.\t\t\t\t\tältere sprache"
   $w insert end "\nastron.\t\t\t\t\tastronomie, astronomisch"
   $w insert end "\nattr.\t\t\t\t\tattribut"
   $w insert end "\naufl.\t\t\t\t\tauflage"
   $w insert end "\nausg.\t\t\t\t\tausgabe"
   $w insert end "\nav., avest., awest.\t\t\t\t\tawestisch"
   $w insert end "\nawfries.\t\t\t\t\taltwestfriesisch"
   $w insert end "\nbad.\t\t\t\t\tbadisch"
   $w insert end "\nbair.\t\t\t\t\tbairisch"
   $w insert end "\nbalt.\t\t\t\t\tbaltisch"
   $w insert end "\nbask.\t\t\t\t\tbaskisch"
   $w insert end "\nbasl.\t\t\t\t\tbaslerisch"
   $w insert end "\nbayer., bayr.\t\t\t\t\tbayrisch, bairisch"
   $w insert end "\nbed.\t\t\t\t\tbedeutung"
   $w insert end "\nbeil.\t\t\t\t\tbeilage"
   $w insert end "\nbelg.\t\t\t\t\tbelgisch"
   $w insert end "\nbergm.\t\t\t\t\tbergmännisch"
   $w insert end "\nberl.\t\t\t\t\tberlinisch"
   $w insert end "\nbern.\t\t\t\t\tbernisch"
   $w insert end "\nbes.\t\t\t\t\tbesonders"
   $w insert end "\nbest.\t\t\t\t\tbestimmt"
   $w insert end "\nbetr.\t\t\t\t\tbetreffend"
   $w insert end "\nbez.\t\t\t\t\tbezeichnen, bezeichnung"
   $w insert end "\nbez., bezw.\t\t\t\t\tbeziehungsweise"
   $w insert end "\nbildl.\t\t\t\t\tbildlich"
   $w insert end "\nböhm.\t\t\t\t\tböhmisch (tschechisch)"
   $w insert end "\n\n\Bd.33, S. 1090\n" pnr
   $w insert end "\nböot.\t\t\t\t\tböotisch"
   $w insert end "\nbotan.\t\t\t\t\tbotanisch"
   $w insert end "\nbrabant.\t\t\t\t\tbrabantisch"
   $w insert end "\nbrandenb.\t\t\t\t\tbrandenburgisch"
   $w insert end "\nbrem.\t\t\t\t\tbremisch"
   $w insert end "\nbret.\t\t\t\t\tbretonisch"
   $w insert end "\nbsl.\t\t\t\t\tbaltoslawisch"
   $w insert end "\nbulg.\t\t\t\t\tbulgarisch"
   $w insert end "\nburg.\t\t\t\t\tburgundisch"
   $w insert end "\nbzw.\t\t\t\t\tbeziehungsweise"
   $w insert end "\nc., ca.\t\t\t\t\tzirka"
   $w insert end "\ncambr.\t\t\t\t\tkambrisch"
   $w insert end "\ncap.\t\t\t\t\tkapitel"
   $w insert end "\n"
   $w insert end "[format %c 269]"
   $w insert end "ech.\t\t\t\t\ttschechisch"
   $w insert end "\ncf.\t\t\t\t\tconfer (vergleiche)"
   $w insert end "\ncimbr.\t\t\t\t\tcimbrisch"
   $w insert end "\ncit.\t\t\t\t\tzitiert"
   $w insert end "\nclev.\t\t\t\t\tklevisch"
   $w insert end "\ncod.\t\t\t\t\tkodex"
   $w insert end "\ncoll.\t\t\t\t\tkollektivum"
   $w insert end "\ncomp.\t\t\t\t\tkomparativ"
   $w insert end "\ncomp., compos.\t\t\t\t\tkompositum"
   $w insert end "\ncompos.-typ.\t\t\t\t\tkompositionstypus"
   $w insert end "\nconj.\t\t\t\t\tkonjugation, konjunktion,"
   $w insert end "\n\t\t\t\t\tkonjunktiv"
   $w insert end "\nconjunct.\t\t\t\t\tkonjunktion, konjunktiv"
   $w insert end "\ncons.\t\t\t\t\tkonsonant, konsonantisch"
   $w insert end "\ncorn.\t\t\t\t\tkornisch"
   $w insert end "\ncymr.\t\t\t\t\tkymrisch"
   $w insert end "\nczech.\t\t\t\t\ttschechisch"
   $w insert end "\nd.\t\t\t\t\tder, die, das"
   $w insert end "\ndän.\t\t\t\t\tdänisch"
   $w insert end "\ndas.\t\t\t\t\tdaselbst"
   $w insert end "\ndass.\t\t\t\t\tdasselbe"
   $w insert end "\ndat.\t\t\t\t\tdativ"
   $w insert end "\ndecl., dekl.\t\t\t\t\tdeklination"
   $w insert end "\ndem., demin., deminut.\t\t\t\t\tdiminutiv"
   $w insert end "\ndemonstr.\t\t\t\t\tdemonstrativum"
   $w insert end "\ndesgl.\t\t\t\t\tdesgleichen"
   $w insert end "\nd. h.\t\t\t\t\tdas heiszt"
   $w insert end "\nd. i.\t\t\t\t\tdas ist"
   $w insert end "\ndial.\t\t\t\t\tdialektisch"
   $w insert end "\ndichter.\t\t\t\t\tdichterisch"
   $w insert end "\ndim., dimin., diminut.\t\t\t\t\tdiminutiv"
   $w insert end "\ndithmars.\t\t\t\t\tdithmarsisch"
   $w insert end "\nd. j.\t\t\t\t\tder junge"
   $w insert end "\ndl.\t\t\t\t\tdual"
   $w insert end "\ndpl., d. pl.\t\t\t\t\tdativ plural"
   $w insert end "\nds.\t\t\t\t\tdasselbe"
   $w insert end "\ndt., dtsch.\t\t\t\t\tdeutsch"
   $w insert end "\ndu., dual.\t\t\t\t\tdual(is)"
   $w insert end "\ndüring.\t\t\t\t\tthüringisch"
   $w insert end "\nebd., ebda., ebend.\t\t\t\t\tebenda"
   $w insert end "\neig.\t\t\t\t\teigentlich"
   $w insert end "\neigenn.\t\t\t\t\teigenname"
   $w insert end "\neigtl.\t\t\t\t\teigentlich"
   $w insert end "\neinl.\t\t\t\t\teinleitung"
   $w insert end "\nels., elsäss.\t\t\t\t\telsässisch"
   $w insert end "\nengad.\t\t\t\t\tengadinisch"
   $w insert end "\nengl.\t\t\t\t\tenglisch"
   $w insert end "\nentspr., entsprech.\t\t\t\t\tentsprechend"
   $w insert end "\nepithet.\t\t\t\t\tepitheton"
   $w insert end "\nerg.\t\t\t\t\tergänzt, ergänzung"
   $w insert end "\nerkl.\t\t\t\t\terklärung"
   $w insert end "\nerzgeb.\t\t\t\t\terzgebirgisch"
   $w insert end "\nest., estn.\t\t\t\t\testnisch"
   $w insert end "\netc.\t\t\t\t\tet cetera"
   $w insert end "\netw.\t\t\t\t\tetwas"
   $w insert end "\netymol.\t\t\t\t\tetymologisch"
   $w insert end "\nevangel.\t\t\t\t\tevangelisch"
   $w insert end "\nevtl.\t\t\t\t\teventuell"
   $w insert end "\nf.\t\t\t\t\tfemininum, folgende (seite)"
   $w insert end "\nfem., femin.\t\t\t\t\tfemininum"
   $w insert end "\nff.\t\t\t\t\tfolgende (seiten)"
   $w insert end "\nfg.\t\t\t\t\tfolgende (seite)"
   $w insert end "\nfinn.\t\t\t\t\tfinnisch"
   $w insert end "\nfläm.\t\t\t\t\tflämisch"
   $w insert end "\nflect.\t\t\t\t\tflektieren"
   $w insert end "\nflex.\t\t\t\t\tflexion"
   $w insert end "\nfolg.\t\t\t\t\tfolgende (seite)"
   $w insert end "\nfr.\t\t\t\t\tfränkisch, französisch,"
   $w insert end "\n\t\t\t\t\tfriesisch"
   $w insert end "\nfragm.\t\t\t\t\tfragment"
   $w insert end "\nfränk.\t\t\t\t\tfränkisch"
   $w insert end "\nfranz., französ.\t\t\t\t\tfranzösisch"
   $w insert end "\nfriaul.\t\t\t\t\tfriaulisch"
   $w insert end "\nfries.\t\t\t\t\tfriesisch"
   $w insert end "\nfrk.\t\t\t\t\tfränkisch"
   $w insert end "\nfrz.\t\t\t\t\tfranzösisch"
   $w insert end "\nfut.\t\t\t\t\tfuturum"
   $w insert end "\ng.\t\t\t\t\tgotisch"
   $w insert end "\ngäl.\t\t\t\t\tgälisch"
   $w insert end "\ngall.\t\t\t\t\tgallisch"
   $w insert end "\ngedr.\t\t\t\t\tgedruckt"
   $w insert end "\ngen., genit.\t\t\t\t\tgenitiv"
   $w insert end "\ngerm., german.\t\t\t\t\tgermanisch"
   $w insert end "\ngeschr.\t\t\t\t\tgeschrieben"
   $w insert end "\ngespr.\t\t\t\t\tgesprochen"
   $w insert end "\ngl.\t\t\t\t\tglosse"
   $w insert end "\ngleichbed.\t\t\t\t\tgleichbedeutend"
   $w insert end "\ngloss.\t\t\t\t\tglosse"
   $w insert end "\ngot., goth.\t\t\t\t\tgotisch"
   $w insert end "\ngotl.\t\t\t\t\tgotländisch"
   $w insert end "\ngött., götting.\t\t\t\t\tgöttingisch"
   $w insert end "\ngr.\t\t\t\t\tgriechisch"
   $w insert end "\ngramm.\t\t\t\t\tgrammatisch"
   $w insert end "\ngriech\t\t\t\t\tgriechisch"
   $w insert end "\ngrönl.\t\t\t\t\tgrönländisch"
   $w insert end "\ngs.\t\t\t\t\tgegensatz"
   $w insert end "\ngth.\t\t\t\t\tgegenteil"
   $w insert end "\nhalbma.\t\t\t\t\thalbmundart"
   $w insert end "\nhamb.\t\t\t\t\thamburgisch"
   $w insert end "\nhandschr.\t\t\t\t\thandschrift"
   $w insert end "\n\n\Bd. 33, S. 1091\n" pnr
   $w insert end "\nhandschuhsh.\t\t\t\t\thandschuhsheimisch"
   $w insert end "\nhaupts.\t\t\t\t\thauptsächlich"
   $w insert end "\nhd.\t\t\t\t\thochdeutsch"
   $w insert end "\nhdschr.\t\t\t\t\thandschrift"
   $w insert end "\nhebr.\t\t\t\t\thebräisch"
   $w insert end "\nhelgoländ.\t\t\t\t\thelgoländisch"
   $w insert end "\nhenneb., henneberg.\t\t\t\t\thennebergisch"
   $w insert end "\nhess.\t\t\t\t\thessisch"
   $w insert end "\nhist., histor.\t\t\t\t\thistorisch"
   $w insert end "\nhochd., hochdt.\t\t\t\t\thochdeutsch"
   $w insert end "\nholl., holländ.\t\t\t\t\tholländisch"
   $w insert end "\nholst., holstein.\t\t\t\t\tholsteinisch"
   $w insert end "\nhom.\t\t\t\t\thomerisch"
   $w insert end "\nhs., hss.\t\t\t\t\thandschrift, handschriften"
   $w insert end "\ni. a.\t\t\t\t\tim allgemeinen"
   $w insert end "\nib.\t\t\t\t\tibidem"
   $w insert end "\nidg.\t\t\t\t\tindogermanisch"
   $w insert end "\ni. gegs.\t\t\t\t\tim gegensatz"
   $w insert end "\nimp., imper.\t\t\t\t\timperativ"
   $w insert end "\nimperf.\t\t\t\t\timperfekt"
   $w insert end "\nind.\t\t\t\t\tindikativ"
   $w insert end "\nindekl.\t\t\t\t\tindeklinabel"
   $w insert end "\nindic.\t\t\t\t\tindikativ"
   $w insert end "\nindog., indogerm.\t\t\t\t\tindogermanisch"
   $w insert end "\ninf., infin.\t\t\t\t\tinfinitiv"
   $w insert end "\ninl.\t\t\t\t\tinlautend"
   $w insert end "\ninsbes.\t\t\t\t\tinsbesondere"
   $w insert end "\ninstr.\t\t\t\t\tinstrumental"
   $w insert end "\ninterj.\t\t\t\t\tinterjektion"
   $w insert end "\nintr., intrans.\t\t\t\t\tintransitiv"
   $w insert end "\nir.\t\t\t\t\tirisch"
   $w insert end "\niran.\t\t\t\t\tiranisch"
   $w insert end "\nisl., isländ.\t\t\t\t\tisländisch"
   $w insert end "\nit., ital.\t\t\t\t\titalienisch"
   $w insert end "\niterat., iterativ.\t\t\t\t\titerativum"
   $w insert end "\njahrh.\t\t\t\t\tjahrhundert"
   $w insert end "\njem., jemd.\t\t\t\t\tjemand"
   $w insert end "\njg.\t\t\t\t\tjünger"
   $w insert end "\njh.\t\t\t\t\tjahrhundert"
   $w insert end "\njmd.\t\t\t\t\tjemand"
   $w insert end "\nkärnt.\t\t\t\t\tkärntnisch"
   $w insert end "\nkatal.\t\t\t\t\tkatalanisch"
   $w insert end "\nkathol.\t\t\t\t\tkatholisch"
   $w insert end "\nkelt.\t\t\t\t\tkeltisch"
   $w insert end "\nklruss.\t\t\t\t\tkleinrussisch"
   $w insert end "\nköln.\t\t\t\t\tkölnisch"
   $w insert end "\nkomp.\t\t\t\t\tkompositum"
   $w insert end "\nkonj.\t\t\t\t\tkonjunktiv"
   $w insert end "\nkons.\t\t\t\t\tkonsonant, konsonantisch"
   $w insert end "\nkorn.\t\t\t\t\tkornisch"
   $w insert end "\nkroat.\t\t\t\t\tkroatisch"
   $w insert end "\nkymr.\t\t\t\t\tkymrisch"
   $w insert end "\nl.\t\t\t\t\tlies"
   $w insert end "\nlad.\t\t\t\t\tladinisch"
   $w insert end "\nlandw.\t\t\t\t\tlandwirtschaft"
   $w insert end "\nlangob.\t\t\t\t\tlangobardisch"
   $w insert end "\nlapp.\t\t\t\t\tlappisch"
   $w insert end "\nlat.\t\t\t\t\tlateinisch"
   $w insert end "\nlaus.\t\t\t\t\tlausitzisch"
   $w insert end "\nlett.\t\t\t\t\tlettisch"
   $w insert end "\nlexikal.\t\t\t\t\tlexikalisch"
   $w insert end "\nliefl.\t\t\t\t\tlivländisch"
   $w insert end "\nlipp.\t\t\t\t\tlippisch"
   $w insert end "\nlit.\t\t\t\t\tlitauisch"
   $w insert end "\nliter., literar.\t\t\t\t\tliterarisch"
   $w insert end "\nlitt.\t\t\t\t\tlitauisch"
   $w insert end "\nliturg.\t\t\t\t\tliturgisch"
   $w insert end "\nlivl.\t\t\t\t\tlivländisch"
   $w insert end "\nlocat.\t\t\t\t\tlokativ"
   $w insert end "\nlomb.\t\t\t\t\tlombardisch"
   $w insert end "\nlothr.\t\t\t\t\tlothringisch"
   $w insert end "\nlux., luxemb.\t\t\t\t\tluxemburgisch"
   $w insert end "\nm.\t\t\t\t\tmaskulinum"
   $w insert end "\nma.\t\t\t\t\tmittelalter, mittelalterlich"
   $w insert end "\nma., maa.\t\t\t\t\tmundart, mundarten"
   $w insert end "\nmagy.\t\t\t\t\tmagyarisch"
   $w insert end "\nmailänd.\t\t\t\t\tmailändisch"
   $w insert end "\nmansf., mansfeld.\t\t\t\t\tmansfeldisch"
   $w insert end "\nmärk.\t\t\t\t\tmärkisch"
   $w insert end "\nmasc., mask.\t\t\t\t\tmaskulinum"
   $w insert end "\nmd.\t\t\t\t\tmitteldeutsch"
   $w insert end "\nmda.\t\t\t\t\tmundart"
   $w insert end "\nme.\t\t\t\t\tmittelenglisch"
   $w insert end "\nmeckl., mecklb., \t\t\t\t\tmecklenburgisch"
   $w insert end "\nmecklenb."
   $w insert end "\nmed.\t\t\t\t\tmedium"
   $w insert end "\nmed., medic., medicin.\t\t\t\t\tmedizinisch"
   $w insert end "\nmeining.\t\t\t\t\tmeiningisch"
   $w insert end "\nmeiszn.\t\t\t\t\tmeisznisch"
   $w insert end "\nmengl.\t\t\t\t\tmittelenglisch"
   $w insert end "\nmetath.\t\t\t\t\tmetathese"
   $w insert end "\nmfr., mfränk., mfrk.\t\t\t\t\tmittelfränkisch"
   $w insert end "\nmgr.\t\t\t\t\tmittelgriechisch"
   $w insert end "\nmhd.\t\t\t\t\tmittelhochdeutsch"
   $w insert end "\nmir.\t\t\t\t\tmittelirisch"
   $w insert end "\nmitt.\t\t\t\t\tmitteilung"
   $w insert end "\nmitteld.\t\t\t\t\tmitteldeutsch"
   $w insert end "\nmittelfr.\t\t\t\t\tmittelfränkisch"
   $w insert end "\nmittell.\t\t\t\t\tmittellateinisch"
   $w insert end "\nmittl.\t\t\t\t\tmittlerer"
   $w insert end "\nmlat.\t\t\t\t\tmittellateinisch"
   $w insert end "\nmnd., mndd.\t\t\t\t\tmittelniederdeutsch"
   $w insert end "\nmndl., mniederl.,\t\t\t\t\tmittelniederländisch"
   $w insert end "\nmnl., mnld."
   $w insert end "\nmod.\t\t\t\t\tmodern"
   $w insert end "\nmoselfr.\t\t\t\t\tmoselfränkisch"
   $w insert end "\nmostfries.\t\t\t\t\tmittelostfriesisch"
   $w insert end "\nmschwed.\t\t\t\t\tmittelschwedisch"
   $w insert end "\nmscr.\t\t\t\t\tmanuskript"
   $w insert end "\nmundartl.\t\t\t\t\tmundartlich"
   $w insert end "\nmündl.\t\t\t\t\tmündlich"
   $w insert end "\nn.\t\t\t\t\tneu, neutrum"
   $w insert end "\nnass.\t\t\t\t\tnassauisch"
   $w insert end "\n\n\Bd. 33, S. 1092\n" pnr
   $w insert end "\nnd.\t\t\t\t\tniederdeutsch"
   $w insert end "\nndalem.\t\t\t\t\tniederalemannisch"
   $w insert end "\nndd.\t\t\t\t\tniederdeutsch"
   $w insert end "\nndf.\t\t\t\t\tnordfriesisch"
   $w insert end "\nndl.\t\t\t\t\tniederländisch"
   $w insert end "\nndrh.\t\t\t\t\tniederrheinisch"
   $w insert end "\nndsächs.\t\t\t\t\tniedersächsisch"
   $w insert end "\nne.\t\t\t\t\tneuenglisch"
   $w insert end "\nneapol.\t\t\t\t\tneapolitanisch"
   $w insert end "\nnengl.\t\t\t\t\tneuenglisch"
   $w insert end "\nneufr.\t\t\t\t\tneufranzösisch"
   $w insert end "\nneutr.\t\t\t\t\tneutrum"
   $w insert end "\nnfr.\t\t\t\t\tneufranzösisch"
   $w insert end "\nnfr., nfränk.\t\t\t\t\tniederfränkisch"
   $w insert end "\nnfries.\t\t\t\t\tneufriesisch"
   $w insert end "\nnfrk.\t\t\t\t\tniederfränkisch"
   $w insert end "\nngr.\t\t\t\t\tneugriechisch"
   $w insert end "\nnhd.\t\t\t\t\tneuhochdeutsch"
   $w insert end "\nniederd.\t\t\t\t\tniederdeutsch"
   $w insert end "\nniederl.\t\t\t\t\tniederländisch"
   $w insert end "\nniederrh.\t\t\t\t\tniederrheinisch"
   $w insert end "\nnisl.\t\t\t\t\tneuisländisch"
   $w insert end "\nnl.\t\t\t\t\tniederländisch"
   $w insert end "\nnlaus.\t\t\t\t\tniederlausitzisch"
   $w insert end "\nnld.\t\t\t\t\tniederländisch"
   $w insert end "\nnnd.\t\t\t\t\tneuniederdeutsch"
   $w insert end "\nnndl., nnl., nnld.\t\t\t\t\tneuniederländisch"
   $w insert end "\nnnorw.\t\t\t\t\tneunorwegisch"
   $w insert end "\nno.\t\t\t\t\tnummer"
   $w insert end "\nnö.\t\t\t\t\tnordöstlich"
   $w insert end "\nnom.\t\t\t\t\tnomen, nominativ"
   $w insert end "\nnord.\t\t\t\t\tnordisch"
   $w insert end "\nnordböhm.\t\t\t\t\tnordböhmisch (deutsch in"
   $w insert end "\n\t\t\t\t\tNordböhmen)"
   $w insert end "\nnordd.\t\t\t\t\tnorddeutsch"
   $w insert end "\nnordfr.\t\t\t\t\tnordfriesisch"
   $w insert end "\nnorm.\t\t\t\t\tnormannisch"
   $w insert end "\nnorth.\t\t\t\t\tnortheimisch"
   $w insert end "\nnorw., norweg.\t\t\t\t\tnorwegisch"
   $w insert end "\nn. pl.\t\t\t\t\tnominativ plural"
   $w insert end "\nnr.\t\t\t\t\tnummer"
   $w insert end "\nnrh., nrhein.\t\t\t\t\tniederrheinisch"
   $w insert end "\nnsg.\t\t\t\t\tnominativ singular"
   $w insert end "\nnsl.\t\t\t\t\tneuslowenisch"
   $w insert end "\nob.\t\t\t\t\toben"
   $w insert end "\nobd., oberd., oberdt.\t\t\t\t\toberdeutsch"
   $w insert end "\noberpf.\t\t\t\t\toberpfälzisch"
   $w insert end "\noberrh.\t\t\t\t\toberrheinisch"
   $w insert end "\nobers.\t\t\t\t\tobersächsisch"
   $w insert end "\nobj.\t\t\t\t\tobjekt"
   $w insert end "\nobl.\t\t\t\t\tobliquus"
   $w insert end "\nobsächs.\t\t\t\t\tobersächsisch"
   $w insert end "\nobsc.\t\t\t\t\tobszön"
   $w insert end "\nobw.\t\t\t\t\tobwaldnerisch"
   $w insert end "\nod. ä.\t\t\t\t\toder ähnlich"
   $w insert end "\nofr., ofries.\t\t\t\t\tostfriesisch"
   $w insert end "\nöft.\t\t\t\t\töfter(s)"
   $w insert end "\noldenb., oldenburg.\t\t\t\t\toldenburgisch"
   $w insert end "\nomd.\t\t\t\t\tostmitteldeutsch"
   $w insert end "\nopt.\t\t\t\t\toptativ"
   $w insert end "\norig.\t\t\t\t\toriginal"
   $w insert end "\nosk.\t\t\t\t\toskisch"
   $w insert end "\nosnabr.\t\t\t\t\tosnabrückisch"
   $w insert end "\nosterl.\t\t\t\t\tosterländisch"
   $w insert end "\nösterr. österreich.\t\t\t\t\tösterreichisch"
   $w insert end "\nostfäl.\t\t\t\t\tostfälisch"
   $w insert end "\nostfr.\t\t\t\t\tostfriesisch"
   $w insert end "\nöstr.\t\t\t\t\tösterreichisch"
   $w insert end "\npaion.\t\t\t\t\tpäonisch"
   $w insert end "\npart.\t\t\t\t\tpartikel"
   $w insert end "\npart., partic.\t\t\t\t\tpartizip"
   $w insert end "\npartiz.-adj.\t\t\t\t\tpartizipialadjektiv"
   $w insert end "\npass.\t\t\t\t\tpassiv"
   $w insert end "\nperf.\t\t\t\t\tperfekt"
   $w insert end "\npers.\t\t\t\t\tpersisch, person, persönlich"
   $w insert end "\npfälz.\t\t\t\t\tpfälzisch"
   $w insert end "\npiem.\t\t\t\t\tpiemontesisch"
   $w insert end "\npl.\t\t\t\t\tplural"
   $w insert end "\nplattd.\t\t\t\t\tplattdeutsch"
   $w insert end "\nplur.\t\t\t\t\tplural"
   $w insert end "\npoln.\t\t\t\t\tpolnisch"
   $w insert end "\nport., portug.\t\t\t\t\tportugiesisch"
   $w insert end "\npos.\t\t\t\t\tpositiv"
   $w insert end "\np. prt.\t\t\t\t\tpartizipium präteriti"
   $w insert end "\npraep., präp(os).\t\t\t\t\tpräposition"
   $w insert end "\npraes., präs.\t\t\t\t\tpräsens"
   $w insert end "\npraet., prät(er).\t\t\t\t\tpräteritum"
   $w insert end "\npreusz.\t\t\t\t\tpreuszisch"
   $w insert end "\npron.\t\t\t\t\tpronomen"
   $w insert end "\nprov., provenc.\t\t\t\t\tprovenzalisch"
   $w insert end "\nps.\t\t\t\t\tpsalm"
   $w insert end "\npsychol.\t\t\t\t\tpsychologisch"
   $w insert end "\nqu. a. d. (17. jh.)\t\t\t\t\tquelle aus dem"
   $w insert end "\n\t\t\t\t\t(17. jahrhundert)"
   $w insert end "\nqu. v. j.\t\t\t\t\tquelle vom jahre"
   $w insert end "\nredupl.\t\t\t\t\treduplizierend"
   $w insert end "\nrefl.\t\t\t\t\treflexiv"
   $w insert end "\nrelat.\t\t\t\t\trelativum"
   $w insert end "\nresp.\t\t\t\t\trespektive"
   $w insert end "\nrhein.\t\t\t\t\trheinisch"
   $w insert end "\nrheinfr., rhfrk.\t\t\t\t\trheinfränkisch"
   $w insert end "\nripuar.\t\t\t\t\tripuarisch"
   $w insert end "\nrom., roman.\t\t\t\t\tromanisch"
   $w insert end "\nrthlr.\t\t\t\t\treichstaler"
   $w insert end "\nrumän.\t\t\t\t\trumänisch"
   $w insert end "\nruss.\t\t\t\t\trussisch"
   $w insert end "\ns.\t\t\t\t\tseite, siehe"
   $w insert end "\nsächs.\t\t\t\t\tsächsisch"
   $w insert end "\nsaml.\t\t\t\t\tsamländisch"
   $w insert end "\nsanskr., sanskrit.\t\t\t\t\tsanskritisch"
   $w insert end "\nsard.\t\t\t\t\tsardinisch"
   $w insert end "\nsaterl., saterländ.,\t\t\t\t\tsaterländisch"
   $w insert end "\nsaterld."
   $w insert end "\nsatir.\t\t\t\t\tsatirisch"
   $w insert end "\ns. b.\t\t\t\t\tsiehe besonders"
   $w insert end "\n\n\Bd. 33, S. 1093\n" pnr
   $w insert end "\nsc.\t\t\t\t\tscilicet"
   $w insert end "\nschles.\t\t\t\t\tschlesisch"
   $w insert end "\nschlesw.\t\t\t\t\tschleswigisch"
   $w insert end "\nschmalkald.\t\t\t\t\tschmalkaldisch"
   $w insert end "\nschott.\t\t\t\t\tschottisch"
   $w insert end "\nschw.\t\t\t\t\tschwach, schwedisch"
   $w insert end "\nschwäb.\t\t\t\t\tschwäbisch"
   $w insert end "\nschwed.\t\t\t\t\tschwedisch"
   $w insert end "\nschweiz., schweizer.\t\t\t\t\tschweizerisch"
   $w insert end "\nschwm.\t\t\t\t\tschwaches maskulinum"
   $w insert end "\nscil.\t\t\t\t\tscilicet"
   $w insert end "\ns. d.\t\t\t\t\tsiehe dort"
   $w insert end "\nsec.\t\t\t\t\tsekundär"
   $w insert end "\nsemit.\t\t\t\t\tsemitisch"
   $w insert end "\nserb.\t\t\t\t\tserbisch"
   $w insert end "\nserbokr.\t\t\t\t\tserbokroatisch"
   $w insert end "\nsg., sgl.\t\t\t\t\tsingular"
   $w insert end "\nsiebenb.\t\t\t\t\tsiebenbürgisch"
   $w insert end "\nsing.\t\t\t\t\tsingular"
   $w insert end "\nskr., skrt.\t\t\t\t\tsanskritisch"
   $w insert end "\nsl., slav., slaw.\t\t\t\t\tslawisch"
   $w insert end "\nslov., sloven., slow.\t\t\t\t\tslowenisch"
   $w insert end "\ns. o., s. ob.\t\t\t\t\tsiehe oben"
   $w insert end "\nsog.\t\t\t\t\tsogenannt"
   $w insert end "\nsorb.\t\t\t\t\tsorbisch"
   $w insert end "\nsp.\t\t\t\t\tspalte"
   $w insert end "\nsp., span.\t\t\t\t\tspanisch"
   $w insert end "\nspec.\t\t\t\t\tspeziell"
   $w insert end "\nspecif.\t\t\t\t\tspezifisch"
   $w insert end "\nspez.\t\t\t\t\tspeziell"
   $w insert end "\nspr.\t\t\t\t\tsprache, sprich, sprüche"
   $w insert end "\nsprichw., sprw.\t\t\t\t\tsprichwort"
   $w insert end "\nst.\t\t\t\t\tstark, stelle"
   $w insert end "\nsteir.\t\t\t\t\tsteirisch"
   $w insert end "\nstf.\t\t\t\t\tstarkes femininum"
   $w insert end "\nstm.\t\t\t\t\tstarkes maskulinum"
   $w insert end "\nstr.\t\t\t\t\tstrophe"
   $w insert end "\ns. u.\t\t\t\t\tsiehe unten"
   $w insert end "\ns. u. a.\t\t\t\t\tsiehe unter anderem"
   $w insert end "\nsubj.\t\t\t\t\tsubjekt"
   $w insert end "\nsubst.\t\t\t\t\tsubstantiv, substantiviert"
   $w insert end "\nsüdd., süddt.\t\t\t\t\tsüddeutsch"
   $w insert end "\nsup., superl.\t\t\t\t\tsuperlativ"
   $w insert end "\nsuppl.\t\t\t\t\tsupplement"
   $w insert end "\ns. v.\t\t\t\t\tsub voce"
   $w insert end "\ns. v. a.\t\t\t\t\tso viel als"
   $w insert end "\ns. v. w.\t\t\t\t\tso viel wie"
   $w insert end "\nsw.\t\t\t\t\tschwach"
   $w insert end "\nswf.\t\t\t\t\tschwaches femininum"
   $w insert end "\nswn.\t\t\t\t\tschwaches neutrum"
   $w insert end "\nsylt.\t\t\t\t\tsyltisch"
   $w insert end "\nsyn.\t\t\t\t\tsynonym, synonymik"
   $w insert end "\ntautolog.\t\t\t\t\ttautologisch"
   $w insert end "\ntechn.\t\t\t\t\ttechnisch"
   $w insert end "\nten.\t\t\t\t\ttenuis"
   $w insert end "\nterm.\t\t\t\t\tterminus"
   $w insert end "\ntest.\t\t\t\t\ttestament"
   $w insert end "\nth.\t\t\t\t\ttheil"
   $w insert end "\ntheilw.\t\t\t\t\tteilweise"
   $w insert end "\ntheol.\t\t\t\t\ttheologisch"
   $w insert end "\nthrak.\t\t\t\t\tthrakisch"
   $w insert end "\nthür., thüring.\t\t\t\t\tthüringisch"
   $w insert end "\ntirol.\t\t\t\t\ttirolisch"
   $w insert end "\ntoch.\t\t\t\t\ttocharisch"
   $w insert end "\ntr., trans., transit.\t\t\t\t\ttransitiv"
   $w insert end "\ntschech.\t\t\t\t\ttschechisch"
   $w insert end "\nt. t.\t\t\t\t\tterminus technicus"
   $w insert end "\ntürk.\t\t\t\t\ttürkisch"
   $w insert end "\nu.\t\t\t\t\tund"
   $w insert end "\nu. a.\t\t\t\t\tund andere"
   $w insert end "\nu. ä., u. ähnl.\t\t\t\t\tund ähnlich"
   $w insert end "\nu. a. m.\t\t\t\t\tund anderes mehr"
   $w insert end "\nüb.\t\t\t\t\tüber"
   $w insert end "\nübers.\t\t\t\t\tübersetzung"
   $w insert end "\nu. dergl., u. dgl.\t\t\t\t\tund dergleichen"
   $w insert end "\numbr.\t\t\t\t\tumbrisch"
   $w insert end "\nungar., ungr.\t\t\t\t\tungarisch (auch: deutsch"
   $w insert end "\n\t\t\t\t\tin Ungarn)"
   $w insert end "\nunpers.\t\t\t\t\tunpersönlich"
   $w insert end "\nu. o.\t\t\t\t\tund oft"
   $w insert end "\nu. ö.\t\t\t\t\tund öfter"
   $w insert end "\nurk., urkde\t\t\t\t\turkunde"
   $w insert end "\nurkdl.\t\t\t\t\turkundlich"
   $w insert end "\nurspr.\t\t\t\t\tursprünglich"
   $w insert end "\nurverw.\t\t\t\t\turverwandt"
   $w insert end "\nu. s. f.\t\t\t\t\tund so fort"
   $w insert end "\nusw., u. s. w.\t\t\t\t\tund so weiter"
   $w insert end "\nu. zw. bes.\t\t\t\t\tund zwar besonders"
   $w insert end "\nv.\t\t\t\t\tverb"
   $w insert end "\nvandal.\t\t\t\t\twandalisch"
   $w insert end "\nvar.\t\t\t\t\tvariante"
   $w insert end "\nvb., verb.\t\t\t\t\tverb, verbum"
   $w insert end "\nverb.-adj.\t\t\t\t\tverbaladjektiv"
   $w insert end "\nvergl.\t\t\t\t\tvergleiche"
   $w insert end "\nversch.\t\t\t\t\tverschieden"
   $w insert end "\nvgl.\t\t\t\t\tvergleiche"
   $w insert end "\nvgl. u.\t\t\t\t\tvergleiche unten"
   $w insert end "\nviell.\t\t\t\t\tvielleicht"
   $w insert end "\nv. j.\t\t\t\t\tvom jahre"
   $w insert end "\nvläm.\t\t\t\t\tflämisch"
   $w insert end "\nvoc.\t\t\t\t\tvokativ"
   $w insert end "\nvocab.\t\t\t\t\tvocabularius"
   $w insert end "\nvogtl., vogtländ.\t\t\t\t\tvogtländisch"
   $w insert end "\nvor.\t\t\t\t\tvorig"
   $w insert end "\nvorarlberg.\t\t\t\t\tvorarlbergisch"
   $w insert end "\nvulg.\t\t\t\t\tvulgär"
   $w insert end "\nwalach.\t\t\t\t\twalachisch"
   $w insert end "\nwaldeck.\t\t\t\t\twaldeckisch"
   $w insert end "\nwallis.\t\t\t\t\twallisisch"
   $w insert end "\nwallon.\t\t\t\t\twallonisch"
   $w insert end "\nwang., wanger.\t\t\t\t\twangeroogisch"
   $w insert end "\nwbb.\t\t\t\t\twörterbücher"
   $w insert end "\nweidm.\t\t\t\t\tweidmännisch"
   $w insert end "\nwend.\t\t\t\t\twendisch"
   $w insert end "\nwestböhm.\t\t\t\t\twestböhmisch (deutsch in"
   $w insert end "\n\t\t\t\t\tWestböhmen)"
   $w insert end "\n\n\Bd. 33, S. 1094\n" pnr
   $w insert end "\nwesterw., westerwäld.\t\t\t\t\twesterwäldisch"
   $w insert end "\nwestf., westfäl.\t\t\t\t\twestfälisch"
   $w insert end "\nwestfr.\t\t\t\t\twestfriesisch"
   $w insert end "\nwestgm.\t\t\t\t\twestgermanisch"
   $w insert end "\nwests.\t\t\t\t\twestsächsisch"
   $w insert end "\nwf.\t\t\t\t\twestfriesisch"
   $w insert end "\nwfläm.\t\t\t\t\twestflämisch"
   $w insert end "\nwfries.\t\t\t\t\twestfriesisch"
   $w insert end "\nwgerm.\t\t\t\t\twestgermanisch"
   $w insert end "\nws.\t\t\t\t\twestsächsisch"
   $w insert end "\nwürtt.\t\t\t\t\twürttembergisch"
   $w insert end "\nwürzb.\t\t\t\t\twürzburgisch"
   $w insert end "\nwz.\t\t\t\t\twurzel"
   $w insert end "\nzahlw.\t\t\t\t\tzahlwort"
   $w insert end "\nz. b.\t\t\t\t\tzum beispiel"
   $w insert end "\nzend.\t\t\t\t\tzendawestisch"
   $w insert end "\nzss.\t\t\t\t\tzusammensetzung"
   $w insert end "\nz. t., z. th.\t\t\t\t\tzum teil"
   $w insert end "\nzuss., zus.-s.\t\t\t\t\tzusammensetzung"
}