proc ShowAbbrQVZ {w} {
   $w delete 1.0 end
   $w insert end "\nnachstehend sind die gebräuchlichsten abkürzungen aufgelöst. "
   $w insert end "nicht angeführt wurden die abkürzungen für männliche vornamen, "
   $w insert end "da sie im allgemeinen leicht auflösbar sind, und die für "
   $w insert end "sprachwissenschaftliche bezeichnungen, von denen nur die in der "
   $w insert end "fachliteratur üblichen verwendet wurden. im haupttitel wurde gegen "
   $w insert end "die vorlage in der regel nicht abgekürzt.\n\n"
   $w insert end "A\t\t\tanfang (bei zeitangaben)"
   $w insert end "\nabh.\t\t\tabhandlung"
   $w insert end "\nabt.\t\t\tabteilung"
   $w insert end "\nakad.\t\t\takademie"
   $w insert end "\nAnh.\t\t\tAnhalt"
   $w insert end "\nanm.\t\t\tanmerkung"
   $w insert end "\nATB\t\t\taltdeutsche textbibliothek"
   $w insert end "\naufl.\t\t\tauflage"
   $w insert end "\nauftr.\t\t\tauftrag"
   $w insert end "\nausg.\t\t\tausgabe"
   $w insert end "\nausgew.\t\t\tausgewählt"
   $w insert end "\n"
   $w insert end "\nb.\t\t\tbei"
   $w insert end "\nBay.; -bay\t\t\tBayern; -bayern"
   $w insert end "\nbd.; bde.\t\t\tband; bände"
   $w insert end "\nbearb.\t\t\tbearbeitet"
   $w insert end "\nbeitr.\t\t\tbeiträge"
   $w insert end "\nber.\t\t\tbericht"
   $w insert end "\nbes.\t\t\tbesonders, besorgt"
   $w insert end "\nbibl.\t\t\tbibliotheca, bibliothek"
   $w insert end "\nbibl. d. ges.\t\t\tbibliothek der gesamten deutschen"
   $w insert end "\ndt. nat.-lit.\t\t\tnational-literatur"
   $w insert end "\nbl.\t\t\tblatt"
   $w insert end "\nBndr.\t\t\tBerliner neudruck(e)"
   $w insert end "\nBr.\t\t\tBreisgau"
   $w insert end "\nBrandenb.\t\t\tBrandenburg"
   $w insert end "\nbzw.\t\t\tbeziehungsweise"
   $w insert end "\n"
   $w insert end "\ncl.\t\t\tclasse"
   $w insert end "\ncop.\t\t\tcopyright"
   $w insert end "\n"
   $w insert end "\nd.\t\t\tder, die, das"
   $w insert end "\nd. ä.\t\t\tder ältere (im ansatz d. verfassernamens"
   $w insert end "\n\t\t\tin kapitälchen)"
   $w insert end "\ndass.\t\t\tdasselbe"
   $w insert end "\nders.\t\t\tderselbe"
   $w insert end "\ndies.\t\t\tdieselbe"
   $w insert end "\ndiss.\t\t\tdissertation"
   $w insert end "\nd. j.\t\t\tder jüngere (im ansatz d. verfassernamens"
   $w insert end "\n\t\t\tin kapitälchen)"
   $w insert end "\nDLD\t\t\tdeutsche literaturdenkmale"
   $w insert end "\nDLE\t\t\tdeutsche literatur in entwicklungsreihen"
   $w insert end "\nDNL\t\t\tdeutsche nationalliteratur (Kürschner)"
   $w insert end "\ndt.\t\t\tdeutsch"
   $w insert end "\nDTM\t\t\tdeutsche texte des mittelalters"
   $w insert end "\ndurchges.\t\t\tdurchgesehen"
   $w insert end "\nDWB\t\t\tdeutsches wörterbuch v. Jac. Grimm u."
   $w insert end "\n\t\t\tWilh. Grimm"
   $w insert end "\n"
   $w insert end "\nE\t\t\tende (bei zeitangaben)"
   $w insert end "\nebd.\t\t\tebenda"
   $w insert end "\neinl.\t\t\teinleitung"
   $w insert end "\nEls.\t\t\tElsaß"
   $w insert end "\nerkl.\t\t\terklärt, erklärung(en)"
   $w insert end "\nersch.\t\t\terschienen"
   $w insert end "\nErzgeb.\t\t\tErzgebirge"
   $w insert end "\nevtl.\t\t\teventuell"
   $w insert end "\n"
   $w insert end "\nf.\t\t\tfür"
   $w insert end "\nf., ff., folg.\t\t\tfolgende"
   $w insert end "\nflugschr. a. d.\t\t\tflugschriften aus den ersten"
   $w insert end "\nersten jahren\t\t\tjahren der reformation"
   $w insert end "\nd. ref."
   $w insert end "\nfortges.\t\t\tfortgesetzt"
   $w insert end "\nfrhr.\t\t\tfreiherr (im ansatz d. verfassernamens in" 
   $w insert end "\n\t\t\tkapitälchen)"
   $w insert end "\n"		
   $w insert end "\ngeb.\t\t\tgebessert, geboren"
   $w insert end "\ngedr.\t\t\tgedruckt"
   $w insert end "\ngen.\t\t\tgenannt"
   $w insert end "\nges.\t\t\tgesammelt"
   $w insert end "\n"
   $w insert end "\nh.\t\t\thälfte (bei zeitangaben), heft"
   $w insert end "\nhg.\t\t\therausgeber"
   $w insert end "\nhg. v.\t\t\therausgegeben von"
   $w insert end "\nhist.\t\t\thistorisch"
   $w insert end "\nHolst.\t\t\tHolstein"
   $w insert end "\nhs.\t\t\thandschrift"
   $w insert end "\n"
   $w insert end "\nimpr.\t\t\timpressum"
   $w insert end "\ninsbes.\t\t\tinsbesondere"
   $w insert end "\n"
   $w insert end "\njg.; jge.\t\t\tjahrgang; jahrgänge"
   $w insert end "\njh.\t\t\tjahrhundert"
   $w insert end "\njun.\t\t\tjunior"
   $w insert end "\n\n\Bd. 33, S. X\n\n" pnr
   $w insert end "\nkath.\t\t\tkatholisch"
   $w insert end "\nkl.\t\t\tklasse"
   $w insert end "\nkr.\t\t\tkreis"
   $w insert end "\n"
   $w insert end "\n-l.\t\t\t-lich"
   $w insert end "\nLaus.\t\t\tLausitz"
   $w insert end "\nlfg.\t\t\tlieferung"
   $w insert end "\nLothr.\t\t\tLothringen"
   $w insert end "\nLV\t\t\tbibliothek des literarischen vereins"
   $w insert end "\n\t\t\tStuttgart"
   $w insert end "\n"
   $w insert end "\nM\t\t\tmitte (bei zeitangaben)"
   $w insert end "\nM.\t\t\tMain"
   $w insert end "\nMecklenb.\t\t\tMecklenburg"
   $w insert end "\nMGH\t\t\tmonumenta Germaniae historica"
   $w insert end "\nmitget.\t\t\tmitgeteilt"
   $w insert end "\nmitt.\t\t\tmitteilung"
   $w insert end "\nmon. Habsb.\t\t\tmonumenta Habsburgica"
   $w insert end "\nms.\t\t\tmanuskript"
   $w insert end "\n"
   $w insert end "\nn\t\t\tnach (bei zeitangaben)"
   $w insert end "\nnachw.\t\t\tnachwort"
   $w insert end "\nndr.\t\t\tneudruck(e) (Halle)"
   $w insert end "\nn. f.\t\t\tneue folge"
   $w insert end "\nnr.\t\t\tnummer"
   $w insert end "\n"
   $w insert end "\nO.\t\t\tOder"
   $w insert end "\no. ä.\t\t\toder ähnlich"
   $w insert end "\no. j.\t\t\tohne jahr"
   $w insert end "\no. o.\t\t\tohne ort"
   $w insert end "\no. o. u. j.\t\t\tohne ort und jahr"
   $w insert end "\nÖst.\t\t\tÖsterreich"
   $w insert end "\nOldenb.\t\t\tOldenburg"
   $w insert end "\norig.\t\t\toriginal"
   $w insert end "\n"
   $w insert end "\npasqu.\t\t\tpasquille"
   $w insert end "\nphil.\t\t\tphilosophisch"
   $w insert end "\nPr.; -pr.\t\t\tPreußen; -preußen"
   $w insert end "\nprogr.\t\t\tprogramm"
   $w insert end "\nps.\t\t\tpseudonym"
   $w insert end "\n"
   $w insert end "\nQV\t\t\tquellenverzeichnis"
   $w insert end "\n"
   $w insert end "\nref.\t\t\treformation"
   $w insert end "\n"
   $w insert end "\ns.\t\t\tsankt, seite(n), siehe"
   $w insert end "\ns. a.\t\t\tsiehe auch"
   $w insert end "\nSachs.\t\t\tSachsen"
   $w insert end "\nSB\t\t\tsitzungsbericht(e)"
   $w insert end "\nSchles.\t\t\tSchlesien"
   $w insert end "\nSchlesw.\t\t\tSchleswig"
   $w insert end "\ns. d.\t\t\tsiehe dort"
   $w insert end "\nsen.\t\t\tsenior"
   $w insert end "\nslg.\t\t\tsammlung"
   $w insert end "\nsp.\t\t\tspäter, spalte"
   $w insert end "\nst.\t\t\tsankt"
   $w insert end "\nsuppl.\t\t\tsupplement"
   $w insert end "\n"
   $w insert end "\nt.\t\t\tteil"
   $w insert end "\nThür.\t\t\tThüringen"
   $w insert end "\ntle.\t\t\tteile"
   $w insert end "\ntsd.\t\t\ttausend"
   $w insert end "\nTSM\t\t\ttexte des späten mittelalters"
   $w insert end "\n"
   $w insert end "\nu\t\t\tum (bei zeitangaben)"
   $w insert end "\nu.\t\t\tund"
   $w insert end "\nu. a.\t\t\tund andere, unter anderem"
   $w insert end "\nu. d. ps.\t\t\tunter dem pseudonym"
   $w insert end "\nu. d. t.\t\t\tunter dem titel"
   $w insert end "\nübers.\t\t\tübersetzer, übersetzt, übersetzung"
   $w insert end "\numgearb.\t\t\tumgearbeitet"
   $w insert end "\nu. ö.\t\t\tund öfter"
   $w insert end "\n"
   $w insert end "\nv\t\t\tvor (bei zeitangaben)"
   $w insert end "\nv.\t\t\tvon"
   $w insert end "\nver.\t\t\tverein"
   $w insert end "\nveränd.\t\t\tverändert"
   $w insert end "\nverb.\t\t\tverbessert"
   $w insert end "\nverf.\t\t\tverfasser, verfaßt"
   $w insert end "\nverh.\t\t\tverheiratete"
   $w insert end "\nverl.\t\t\tverlegt"
   $w insert end "\nverm.\t\t\tvermehrt"
   $w insert end "\nversch.\t\t\tverschieden"
   $w insert end "\nVogtld.\t\t\tVogtland"
   $w insert end "\nvollst.\t\t\tvollständig"
   $w insert end "\n"
   $w insert end "\nwb.\t\t\twörterbuch"
   $w insert end "\nWestf.\t\t\tWestfalen"
   $w insert end "\nWndr.\t\t\tWiener neudruck(e)"
   $w insert end "\nWürtt.\t\t\tWürttemberg"
   $w insert end "\n"
   $w insert end "\nz.\t\t\tzum, zur"
   $w insert end "\nz. b.\t\t\tzum beispiel"
   $w insert end "\nzfda.\t\t\tzeitschrift für deutsches altertum"
   $w insert end "\nzfdph.\t\t\tzeitschrift für deutsche philologie"
   $w insert end "\nzfdwf.\t\t\tzeitschrift für deutsche wortforschung"
   $w insert end "\nzit.\t\t\tzitat, zitiert, zitierung"
   $w insert end "\nzs.\t\t\tzeitschrift"
   $w insert end "\nzw.\t\t\tzwischen"
}