proc ShowUserinfos {w} {
   $w delete 1.0 end
   $w insert end "\nT i t e l a n s a t z"
   $w insert end "\n\nDie Titel werden in alphabetischer Reihenfolge angeführt. Die "
   $w insert end "Titelangaben wurden an den Originalen oder an bibliographischen "
   $w insert end "Hilfsmitteln überprüft. nicht verifizierte Titel sind durch * "
   $w insert end "bezeichnet."
   $w insert end "\nDie für das DWB geltende Schreibweise ist auch im Quellenverzeichnis "
   $w insert end "beibehalten. Jedoch wird auf die Auflösung der Ligatur ß in sz in den "
   $w insert end "Titelangaben verzichtet. ß wird bei der alphabetischen Einordnung als "
   $w insert end "sz gewertet; ä, ö, ü als ae, oe, ue."
   $w insert end "\nÜbersetzungen werden - entsprechend der Zitierweise im DWB, aber "
   $w insert end "abweichend von der Praxis in Bibliotheken - in der Regel unter dem "
   $w insert end "Namen des Übersetzers und nicht unter dem des Originalautors "
   $w insert end "angeführt."
   $w insert end "\nAnonyme Titel sind bei unterschiedlicher Schreibung des ersten "
   $w insert end "Ordnungswortes (z. B. chronik, chronica, kronik usw.) unter der "
   $w insert end "modernen orthographischen Form vereinigt. Darüber hinaus sind "
   $w insert end "gelegentlich zusammengehörige Werke trotz verschiedenen Titelwortlauts "
   $w insert end "unter einem geeigneten Stichwort zusammengefaßt worden (z. B. Faust). "
   $w insert end "Die innere Ordnung derartiger Gruppen wird durch Sperrung der zweiten "
   $w insert end "Ordnungsbegriffe (z. B. kennzeichnende Attribute, Herausgebernamen, "
   $w insert end "Erscheinungsjahre) deutlich gemacht. Auf Gruppenansätze wird stets "
   $w insert end "verwiesen."
   $w insert end "\nDie Angabe des Herausgebers erfolgt gewöhnlich in der "
   $w insert end "vereinheitlichten Kurzform \"hg. v.\". Die Namen der Erscheinungsorte "
   $w insert end "werden meist in normalisierter (und verdeutschter) Form gegeben. "
   $w insert end "\nDie Gesamtzahl der Bände wird durch eine römische Zahl ausgedrückt. "
   $w insert end "In Angaben wie \"II in I\" bezeichnet die erste Zahl die "
   $w insert end "Paginationseinheiten, die zweite dagegen (Buchbinder-) Bände oder "
   $w insert end "Ausgabenteile."
   $w insert end "\nÜber die in der Abkürzungsliste aufgeführten Reihenbezeichnungen "
   $w insert end "hinaus sind im Anschluß an die Titel nur solche Reihenbezeichnungen "
   $w insert end "angegeben, die zur Kennzeichnung der Ausgabe oder zur Verifizierung "
   $w insert end "von Zitierweisen unbedingt notwendig sind."
   $w insert end "\nDen Verfassernamen werden nach Möglichkeit"
   $w insert end " Lebensdaten beigegeben. "
   $w insert end "Hiervon ausgenommen sind in der Regel die Verfasser neuerer "
   $w insert end "Sekundärliteratur. Folgt unmittelbar auf den Verfassernamen ein "
   $w insert end "Klammerzusatz (übers.) o. ä., so bezieht er sich auf alle folgenden "
   $w insert end "Titel."
   $w insert end "\nSteht der als Ansatz gewählte Name nicht auf dem Titelblatt (so "
   $w insert end "insbesondere bei anonym erschienenen Werken, die einem Verfasser "
   $w insert end "zugeordnet werden konnten; bei aufgelösten Pseudonymen bekannter "
   $w insert end "Autoren; bei Übersetzungen, deren Übersetzer nicht im Titel genannt "
   $w insert end "ist), so wird dem Titel ein \[---] vorangestellt. Bei nur "
   $w insert end "bibliographisch geprüften Titeln bleibt die Feststellung der "
   $w insert end "Anonymität abhängig von den benutzten Hilfsmitteln. Bei Konkurrenz "
   $w insert end "zwischen wirklichem Namen und Pseudonym erfolgt der Ansatz bei "
   $w insert end "bekannten Autoren unter dem heute geläufigeren Namen, bei "
   $w insert end "unbekannteren unter dem auf dem Titelblatt aufgedruckten Namen. Im "
   $w insert end "Zweifelsfall wird der wirkliche Name bevorzugt."
   $w insert end "\n\nZ u r  Q u e l l e n- u n d  B e l e g p r ü f u n g\n\n"
   $w insert end "Für die Zuordnung der Belege zu den angegebenen Ausgaben kann die "
   $w insert end "Kenntnis der Zitiergewohnheiten von Bedeutung sein. Daher sind im "
   $w insert end "Quellenverzeichnis - insbesondere bei unübersichtlichen "
   $w insert end "Ausgabenverhältnissen - in Virgeln /.../ häufig verwendete oder "
   $w insert end "mißverständliche Zitierweisen angegeben. Für die Stellenangaben gelten "
   $w insert end "hierbei stereotype Muster (1,8 bedeutet in der Regel Band- und Seiten "
   $w insert end "zählung, doch gilt 8 auch für Vers-, Strophen- oder Zeilenzahl; A 8 "
   $w insert end "steht bei Bogenzählung; hochgestellte Buchstaben bezeichnen Spalten "
   $w insert end "oder Rekto und Verso)."
   $w insert end "\nDa die Zitierangaben des DWB nicht immer leicht auflösbar sind, "
   $w insert end "werden im Quellenverzeichnis unter mehreren in Frage kommenden "
   $w insert end "Ausgaben die nachweislich am häufigsten zitierten durch das Zeichen "
   $w insert end "O vor dem titel hervorgehoben. In gleicher Absicht sind die in den "
   $w insert end "Quellenverzeichnissen der DWB-Bände I, II, III, V, VI, VII genannten "
   $w insert end "Werke mit der Notiz --QV I--, --QV II-- (usw.) versehen."
   $w insert end "\n\n\Bd. 33, S. VIII" pnr
   $w insert end "\n\nHierdurch "
   $w insert end "werden die von den betreffenden Bearbeitern bevorzugt zitierten "
   $w insert end "Ausgaben kenntlich gemacht. Aus diesen Quellen ist besonders häufig "
   $w insert end "ohne zureichende Kennzeichnung der Ausgabe zitiert worden. Beim "
   $w insert end "Nachschlagen von Titelangaben in den älteren Quellenverzeichnissen ist "
   $w insert end "zu beachten, daß die Zuordnung der Titel dort häufig nach anderen "
   $w insert end "Prinzipien erfolgte als im vorliegenden Verzeichnis."
   $w insert end "\nDie gängigen Gesamtausgaben eines Autors oder auch sein für das "
   $w insert end "Wörterbuch wichtigstes Werk werden im DWB häufig mit bloßer Angabe des "
   $w insert end "Verfassernamens und der Stellenangabe (also ohne Nennung eines "
   $w insert end "Titelstichworts) zitiert."
   $w insert end "\nWerden im DWB mehrere Belege eines Autors in fortlaufender Reihe "
   $w insert end "zitiert, so steht der Name des Verfassers nur beim ersten Zitat. Im "
   $w insert end "Zweifelsfall empfiehlt es sich daher bei der Prüfung anonymer Titel, "
   $w insert end "im Quellenverzeichnis auch unter dem Autornamen des im Wörterbuch "
   $w insert end "voranstehenden Zitats nachzuschlagen."
   $w insert end "\nBei anonymen Ausgaben, besonders Sammlungen, Anthologien u. dgl., "
   $w insert end "aber in manchen Fällen auch darüber hinaus, steht am Anfang der "
   $w insert end "Titelzitate in den Belegen statt der Verfasserangabe oft der Name des "
   $w insert end "Herausgebers,"
   $w insert end " z. B. '"
   $w insert end "W" ai
   $w insert end "ACKERNAGEL " ar
   $w insert end "kirchenl. " ti
   $w insert end "1,8', "
   $w insert end "'"
   $w insert end "L" ai
   $w insert end "ASZBERG " ar
   $w insert end "liedersaal " ti
   $w insert end "1,8'. Im Quellenverzeichnis sind hier "
   $w insert end "in der Regel Verweise gesetzt."
   $w insert end "\nAndererseits kann die Zitierung von Belegen aus Textsammlungen "
   $w insert end "namentlich in den älteren Teilen des Wörterbuchs auch nach dem Muster "
   $w insert end "'"
   $w insert end "B" ai
   $w insert end "RANT " ar
   $w insert end "elf bücher " ti
   $w insert end  "1,8' oder '"
   $w insert end "S" ai
   $w insert end "ACHS " ar
   $w insert end "zfda" ti
   $w insert end ". 1,8' "
   $w insert end "erfolgen, wobei dann die Angaben zur zitierten Sammlung, Zeitschrift "
   $w insert end "usw. im Quellenverzeichnis an dem für diese Titel geltenden Ort "
   $w insert end "("
   $w insert end "B ü c h e r, Z e i t s c h r i f t"
   $w insert end ") zu suchen sind, während im Zitat ein aus "
   $w insert end "einer derartigen Quelle zitierter Einzelautor ohne verdeutlichenden "
   $w insert end "Zusatz die Stelle der Verfasserangabe für den genannten Gesamttitel "
   $w insert end "einnimmt."
   $w insert end "\nBei Belegen aus Briefwechseln, die nach dem Typus '"
   $w insert end "G" ai
   $w insert end "OETHE " ar
   $w insert end "an Schiller brw. " ti
   $w insert end "1,8' (o. ä.) zitiert sind, muß im "
   $w insert end "Quellenverzeichnis unter dem an zweiter Stelle genannten Namen "
   $w insert end "nachgeschlagen werden, wenn unter dem an erster Stelle genannten kein "
   $w insert end "Aufschluß gefunden wird."
   $w insert end "\nBei der Verifizierung von Belegen ist zu berücksichtigen, daß vor "
   $w insert end "allem die Bearbeiter der älteren Bände nicht selten aus textkritischen "
   $w insert end "Gründen mehr oder weniger eingreifend geändert haben. Eine gewisse "
   $w insert end "Normalisierung bestimmter orthographisch problematischer Belegtexte "
   $w insert end "hat noch bis in die letzte Bearbeitungsperiode hinein stattgefunden."
}