proc getSpecialChars {} {
   set x {}
   set x "${x}gregorian letter we\n"
   set x "${x}\u10f3\n" 
   set x "${x}combining reversed comma above\n"
   set x "${x}\u0314\n" 
   set x "${x}combining comma above\n"
   set x "${x}\u0313\n" 
   set x "${x}e with combining greek koronis and combining acute accent\n"
   set x "${x}\u0065\u0343\u0301\n" 
   set x "${x}e with combining greek kornonis and combining grave accent\n"
   set x "${x}\u0065\u0343\u0300\n" 
   set x "${x}e with combining reversed comma above and combining grave accent\n"
   set x "${x}\u0065\u0314\u0300\n" 
   set x "${x}e with combining reversed comma above and combining acute accent\n"
   set x "${x}\u0065\u0314\u0301\n" 
   set x "${x}e with combining reversed comma above\n"
   set x "${x}\u0065\u0314\n" 
   set x "${x}e with combining comma above right\n"
   set x "${x}\u0065\u0315\n" 
   set x "${x}e with combining grave accent\n"
   set x "${x}\u0065\u0300\n" 
   set x "${x}e with combining acute accent\n"
   set x "${x}\u0065\u0301\n" 
   set x "${x}combining breve\n"
   set x "${x}\u0306\n" 
   set x "${x}combining left half ring above\n"
   set x "${x}\u0351\n"
   return $x
}